
project_id = "aegclwuugreshufvisax"

[functions.woocommerce-proxy]
verify_jwt = true

[functions.tutor-lms-proxy]
verify_jwt = false

[functions.enroll-courses]
verify_jwt = true

[functions.create-woocommerce-customer]
verify_jwt = true
